name: Release

on:
  pull_request:
    branches: [master]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'

      - name: Install dependencies
        run: yarn --frozen-lockfile

      - name: Run tests
        run: yarn test

      - name: Run build
        run: yarn build

      - name: Run release
        run: yarn release
        env:
          GH_TOKEN: ${{vars.GH_TOKEN}}
          NPM_TOKEN: ${{vars.NPM_TOKEN}}
